# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RideCellMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RideCellMap
  pod 'GoogleMaps'

  target 'RideCellMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RideCellMapUITests' do
    # Pods for testing
  end

end
